### ISSUE TITLE
MAP_HUGE_2MB build error Fedora Linux

### ISSUE THREAD

**Issue by Mentorial** [WyvernTKC/cpuminer-gr-avx2#19] opened 2021-09-18 14:11 UTC
I've tried to build it using your nicely explained doc (https://github.com/WyvernTKC/cpuminer-gr-avx2/blob/main/INSTALL_LINUX)

but got some memory allocation error in this fedora linux:
./build.sh

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether gcc needs -traditional... no
checking whether gcc and cc understand -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for sys/sysctl.h... yes
checking whether be32dec is declared... no
checking whether le32dec is declared... no
checking whether be32enc is declared... no
checking whether le32enc is declared... no
checking whether le16dec is declared... no
checking whether le16enc is declared... no
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for getopt_long... yes
checking whether we can compile AVX code... yes
checking whether we can compile XOP code... yes
checking whether we can compile AVX2 code... yes
checking for json_loads in -ljansson... yes
checking for pthread_create in -lpthread... yes
checking for numa_max_node in -lnuma... yes
checking whether __uint128_t is supported... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating compat/Makefile
config.status: creating compat/jansson/Makefile
config.status: creating cpuminer-config.h
config.status: executing depfiles commands
make  all-recursive
make[1]: Entering directory `/home/ec2-user/new/cpuminer-gr-avx2'
Making all in compat
make[2]: Entering directory `/home/ec2-user/new/cpuminer-gr-avx2/compat'
make[3]: Entering directory `/home/ec2-user/new/cpuminer-gr-avx2/compat'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/ec2-user/new/cpuminer-gr-avx2/compat'
make[2]: Leaving directory `/home/ec2-user/new/cpuminer-gr-avx2/compat'
make[2]: Entering directory `/home/ec2-user/new/cpuminer-gr-avx2'
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-cpu-miner.o -MD -MP -MF .deps/cpuminer-cpu-miner.Tpo -c -o cpuminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
mv -f .deps/cpuminer-cpu-miner.Tpo .deps/cpuminer-cpu-miner.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-util.o -MD -MP -MF .deps/cpuminer-util.Tpo -c -o cpuminer-util.o `test -f 'util.c' || echo './'`util.c
mv -f .deps/cpuminer-util.Tpo .deps/cpuminer-util.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-api.o -MD -MP -MF .deps/cpuminer-api.Tpo -c -o cpuminer-api.o `test -f 'api.c' || echo './'`api.c
mv -f .deps/cpuminer-api.Tpo .deps/cpuminer-api.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-sysinfos.o -MD -MP -MF .deps/cpuminer-sysinfos.Tpo -c -o cpuminer-sysinfos.o `test -f 'sysinfos.c' || echo './'`sysinfos.c
mv -f .deps/cpuminer-sysinfos.Tpo .deps/cpuminer-sysinfos.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-algo-gate-api.o -MD -MP -MF .deps/cpuminer-algo-gate-api.Tpo -c -o cpuminer-algo-gate-api.o `test -f 'algo-gate-api.c' || echo './'`algo-gate-api.c
mv -f .deps/cpuminer-algo-gate-api.Tpo .deps/cpuminer-algo-gate-api.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing  -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -mtune=native -Wall  -Iyes/include -MT cpuminer-virtual_memory.o -MD -MP -MF .deps/cpuminer-virtual_memory.Tpo -c -o cpuminer-virtual_memory.o `test -f 'virtual_memory.c' || echo './'`virtual_memory.c
virtual_memory.c: In function ‘AllocateLargePagesMemory’:
virtual_memory.c:313:29: error: ‘MAP_HUGE_SHIFT’ undeclared (first use in this function); did you mean ‘MAP_HUGE_2MB’?
 #define MAP_HUGE_2MB (21 << MAP_HUGE_SHIFT)
                             ^
virtual_memory.c:324:24: note: in expansion of macro ‘MAP_HUGE_2MB’
                        MAP_HUGE_2MB,
                        ^~~~~~~~~~~~
virtual_memory.c:313:29: note: each undeclared identifier is reported only once for each function it appears in
 #define MAP_HUGE_2MB (21 << MAP_HUGE_SHIFT)
                             ^
virtual_memory.c:324:24: note: in expansion of macro ‘MAP_HUGE_2MB’
                        MAP_HUGE_2MB,
                        ^~~~~~~~~~~~
make[2]: *** [cpuminer-virtual_memory.o] Error 1
make[2]: Leaving directory `/home/ec2-user/new/cpuminer-gr-avx2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/new/cpuminer-gr-avx2'
make: *** [all] Error 2
strip: 'cpuminer': No such file

**Comment by michal-zurkowski** [comment] 2021-09-29 06:32
Can you provide some more information?
What is the exact version of the Fedora OS?
What is the version of GCC that you are trying to use to compile the miner?

**Comment by michal-zurkowski** [comment] 2021-10-03 09:45
It will be fixed with the release of 1.2.0
This was caused by systems with old kernels.

**Closed by michal-zurkowski** 2021-10-03 09:45 UTC
